import { NextResponse } from 'next/server'
import { db } from '@/lib/db'

// POST /api/seed - Seed the database with initial data
export async function POST() {
  try {
    // Create Languages
    const languages = await Promise.all([
      db.language.upsert({
        where: { code: 'en' },
        update: {},
        create: { name: 'English', code: 'en' },
      }),
      db.language.upsert({
        where: { code: 'ar' },
        update: {},
        create: { name: 'العربية', code: 'ar' },
      }),
      db.language.upsert({
        where: { code: 'fr' },
        update: {},
        create: { name: 'Français', code: 'fr' },
      }),
      db.language.upsert({
        where: { code: 'es' },
        update: {},
        create: { name: 'Español', code: 'es' },
      }),
      db.language.upsert({
        where: { code: 'de' },
        update: {},
        create: { name: 'Deutsch', code: 'de' },
      }),
    ])

    // Create Categories
    const categories = await Promise.all([
      db.category.upsert({
        where: { slug: 'programming' },
        update: {},
        create: {
          name: 'Programming',
          nameAr: 'البرمجة',
          slug: 'programming',
          icon: 'Code',
          color: '#3B82F6',
          description: 'Learn programming and software development',
        },
      }),
      db.category.upsert({
        where: { slug: 'datascience' },
        update: {},
        create: {
          name: 'Data Science',
          nameAr: 'علم البيانات',
          slug: 'datascience',
          icon: 'Database',
          color: '#10B981',
          description: 'Learn data analysis, machine learning, and AI',
        },
      }),
      db.category.upsert({
        where: { slug: 'math' },
        update: {},
        create: {
          name: 'Mathematics',
          nameAr: 'الرياضيات',
          slug: 'math',
          icon: 'Calculator',
          color: '#F59E0B',
          description: 'Learn mathematics and statistics',
        },
      }),
      db.category.upsert({
        where: { slug: 'business' },
        update: {},
        create: {
          name: 'Business',
          nameAr: 'الأعمال',
          slug: 'business',
          icon: 'Briefcase',
          color: '#EF4444',
          description: 'Learn business and entrepreneurship',
        },
      }),
      db.category.upsert({
        where: { slug: 'design' },
        update: {},
        create: {
          name: 'Design',
          nameAr: 'التصميم',
          slug: 'design',
          icon: 'Palette',
          color: '#8B5CF6',
          description: 'Learn graphic design and UI/UX',
        },
      }),
      db.category.upsert({
        where: { slug: 'languages' },
        update: {},
        create: {
          name: 'Languages',
          nameAr: 'اللغات',
          slug: 'languages',
          icon: 'Languages',
          color: '#EC4899',
          description: 'Learn new languages',
        },
      }),
      db.category.upsert({
        where: { slug: 'personal' },
        update: {},
        create: {
          name: 'Personal Development',
          nameAr: 'التطور الشخصي',
          slug: 'personal',
          icon: 'Heart',
          color: '#14B8A6',
          description: 'Improve yourself and your skills',
        },
      }),
      db.category.upsert({
        where: { slug: 'science' },
        update: {},
        create: {
          name: 'Science',
          nameAr: 'العلوم',
          slug: 'science',
          icon: 'Globe',
          color: '#6366F1',
          description: 'Learn science and research',
        },
      }),
    ])

    // Create Platforms
    const platforms = await Promise.all([
      db.platform.upsert({
        where: { slug: 'coursera' },
        update: {},
        create: {
          name: 'Coursera',
          slug: 'coursera',
          url: 'https://www.coursera.org',
          description: 'Learn from top universities and companies',
        },
      }),
      db.platform.upsert({
        where: { slug: 'edx' },
        update: {},
        create: {
          name: 'edX',
          slug: 'edx',
          url: 'https://www.edx.org',
          description: 'University-level courses from top institutions',
        },
      }),
      db.platform.upsert({
        where: { slug: 'khanacademy' },
        update: {},
        create: {
          name: 'Khan Academy',
          slug: 'khanacademy',
          url: 'https://www.khanacademy.org',
          description: 'Free world-class education for everyone',
        },
      }),
      db.platform.upsert({
        where: { slug: 'freecodecamp' },
        update: {},
        create: {
          name: 'freeCodeCamp',
          slug: 'freecodecamp',
          url: 'https://www.freecodecamp.org',
          description: 'Learn to code for free',
        },
      }),
      db.platform.upsert({
        where: { slug: 'mit' },
        update: {},
        create: {
          name: 'MIT OpenCourseWare',
          slug: 'mit',
          url: 'https://ocw.mit.edu',
          description: 'Free MIT course materials',
        },
      }),
      db.platform.upsert({
        where: { slug: 'harvard' },
        update: {},
        create: {
          name: 'Harvard Online',
          slug: 'harvard',
          url: 'https://online-learning.harvard.edu',
          description: 'Online courses from Harvard University',
        },
      }),
      db.platform.upsert({
        where: { slug: 'google' },
        update: {},
        create: {
          name: 'Google Digital Garage',
          slug: 'google',
          url: 'https://learndigital.withgoogle.com',
          description: 'Free courses from Google',
        },
      }),
      db.platform.upsert({
        where: { slug: 'odin' },
        update: {},
        create: {
          name: 'The Odin Project',
          slug: 'odin',
          url: 'https://www.theodinproject.com',
          description: 'Full stack web development curriculum',
        },
      }),
      db.platform.upsert({
        where: { slug: 'duolingo' },
        update: {},
        create: {
          name: 'Duolingo',
          slug: 'duolingo',
          url: 'https://www.duolingo.com',
          description: 'Learn languages for free',
        },
      }),
      db.platform.upsert({
        where: { slug: 'almentor' },
        update: {},
        create: {
          name: 'Almentor',
          slug: 'almentor',
          url: 'https://www.almentor.net',
          description: 'Arabic online learning platform',
        },
      }),
      db.platform.upsert({
        where: { slug: 'udacity' },
        update: {},
        create: {
          name: 'Udacity',
          slug: 'udacity',
          url: 'https://www.udacity.com',
          description: 'Tech courses and nanodegrees',
        },
      }),
      db.platform.upsert({
        where: { slug: 'codecademy' },
        update: {},
        create: {
          name: 'Codecademy',
          slug: 'codecademy',
          url: 'https://www.codecademy.com',
          description: 'Interactive coding lessons',
        },
      }),
    ])

    // Create Sample Courses
    const languageMap = Object.fromEntries(languages.map(l => [l.code, l.id]))
    const categoryMap = Object.fromEntries(categories.map(c => [c.slug, c.id]))
    const platformMap = Object.fromEntries(platforms.map(p => [p.slug, p.id]))

    const courses = [
      {
        title: 'CS50\'s Introduction to Computer Science',
        titleAr: 'مقدمة في علوم الحاسوب - CS50',
        description: 'Harvard University\'s introduction to the intellectual enterprises of computer science and the art of programming.',
        descriptionAr: 'مقدمة جامعة هارفارد في مشاريع علوم الحاسوب الفكرية وفن البرمجة.',
        url: 'https://cs50.harvard.edu/x/',
        instructor: 'David J. Malan',
        duration: '12 weeks',
        level: 'beginner',
        rating: 4.9,
        enrollments: '4M+',
        price: 'Free',
        certificate: true,
        isFree: true,
        featured: true,
        categoryId: categoryMap['programming'],
        languageId: languageMap['en'],
        platformId: platformMap['harvard'],
      },
      {
        title: 'freeCodeCamp - Full Stack Development',
        titleAr: 'تطوير الويب الشامل - freeCodeCamp',
        description: 'Learn to code for free. Earn certifications. Get hired.',
        descriptionAr: 'تعلم البرمجة مجاناً. احصل على الشهادات. ابدأ عملك.',
        url: 'https://www.freecodecamp.org',
        duration: '3000+ hours',
        level: 'beginner',
        rating: 4.8,
        enrollments: '50M+',
        price: 'Free',
        certificate: true,
        isFree: true,
        featured: true,
        categoryId: categoryMap['programming'],
        languageId: languageMap['en'],
        platformId: platformMap['freecodecamp'],
      },
      {
        title: 'Machine Learning by Andrew Ng',
        titleAr: 'تعلم الآلة مع أندرو إنج',
        description: 'A foundational course in machine learning by Stanford University.',
        descriptionAr: 'دورة أساسية في تعلم الآلة من جامعة ستانفورد.',
        url: 'https://www.coursera.org/learn/machine-learning',
        instructor: 'Andrew Ng',
        duration: '11 weeks',
        level: 'intermediate',
        rating: 4.9,
        enrollments: '5M+',
        price: 'Free to audit',
        certificate: true,
        isFree: true,
        featured: true,
        categoryId: categoryMap['datascience'],
        languageId: languageMap['en'],
        platformId: platformMap['coursera'],
      },
      {
        title: 'Khan Academy - Mathematics',
        titleAr: 'أكاديمية خان - الرياضيات',
        description: 'Free world-class education for anyone, anywhere.',
        descriptionAr: 'تعليم مجاني عالمي المستوى لأي شخص في أي مكان.',
        url: 'https://www.khanacademy.org/math',
        duration: 'Self-paced',
        level: 'beginner',
        rating: 4.8,
        price: 'Free',
        certificate: false,
        isFree: true,
        featured: false,
        categoryId: categoryMap['math'],
        languageId: languageMap['en'],
        platformId: platformMap['khanacademy'],
      },
      {
        title: 'MIT OpenCourseWare - Computer Science',
        titleAr: 'معهد ماساتشوستس - علوم الحاسوب',
        description: 'Free lecture notes, exams, and videos from MIT.',
        descriptionAr: 'محاضرات واختبارات ومقاطع فيديو مجانية من MIT.',
        url: 'https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/',
        duration: 'Self-paced',
        level: 'intermediate',
        rating: 4.9,
        price: 'Free',
        certificate: false,
        isFree: true,
        featured: true,
        categoryId: categoryMap['programming'],
        languageId: languageMap['en'],
        platformId: platformMap['mit'],
      },
      {
        title: 'edX - Data Science Fundamentals',
        titleAr: 'أساسيات علم البيانات - edX',
        description: 'Learn data science fundamentals from top universities.',
        descriptionAr: 'تعلم أساسيات علم البيانات من أفضل الجامعات.',
        url: 'https://www.edx.org/learn/data-science',
        duration: '8 weeks',
        level: 'beginner',
        rating: 4.7,
        price: 'Free to audit',
        certificate: true,
        isFree: true,
        featured: false,
        categoryId: categoryMap['datascience'],
        languageId: languageMap['en'],
        platformId: platformMap['edx'],
      },
      {
        title: 'Google Digital Marketing Course',
        titleAr: 'دورة التسويق الرقمي من جوجل',
        description: 'Master the basics of digital marketing with Google\'s free course.',
        descriptionAr: 'أتقن أساسيات التسويق الرقمي مع دورة جوجل المجانية.',
        url: 'https://learndigital.withgoogle.com/digitalgarage',
        duration: '40 hours',
        level: 'beginner',
        rating: 4.6,
        enrollments: '1M+',
        price: 'Free',
        certificate: true,
        isFree: true,
        featured: false,
        categoryId: categoryMap['business'],
        languageId: languageMap['en'],
        platformId: platformMap['google'],
      },
      {
        title: 'Python for Everybody',
        titleAr: 'بايثون للجميع',
        description: 'Learn to program and analyze data with Python.',
        descriptionAr: 'تعلم البرمجة وتحليل البيانات باستخدام بايثون.',
        url: 'https://www.py4e.com/',
        instructor: 'Charles Severance',
        duration: '8 weeks',
        level: 'beginner',
        rating: 4.8,
        price: 'Free',
        certificate: true,
        isFree: true,
        featured: true,
        categoryId: categoryMap['programming'],
        languageId: languageMap['en'],
        platformId: platformMap['coursera'],
      },
      {
        title: 'Learning How to Learn',
        titleAr: 'تعلم كيف تتعلم',
        description: 'Powerful mental tools to help you master tough subjects.',
        descriptionAr: 'أدوات ذهنية قوية لمساعدتك على إتقان المواد الصعبة.',
        url: 'https://www.coursera.org/learn/learning-how-to-learn',
        instructor: 'Barbara Oakley',
        duration: '4 weeks',
        level: 'beginner',
        rating: 4.8,
        enrollments: '3M+',
        price: 'Free to audit',
        certificate: true,
        isFree: true,
        featured: false,
        categoryId: categoryMap['personal'],
        languageId: languageMap['en'],
        platformId: platformMap['coursera'],
      },
      {
        title: 'The Odin Project - Full Stack JavaScript',
        titleAr: 'مشروع أودين - تطوير الويب الكامل',
        description: 'Learn web development for free with this comprehensive curriculum.',
        descriptionAr: 'تعلم تطوير الويب مجاناً مع هذه المنهجية الشاملة.',
        url: 'https://www.theodinproject.com/',
        duration: '1000+ hours',
        level: 'beginner',
        rating: 4.9,
        price: 'Free',
        certificate: false,
        isFree: true,
        featured: true,
        categoryId: categoryMap['programming'],
        languageId: languageMap['en'],
        platformId: platformMap['odin'],
      },
      {
        title: 'Duolingo - Learn Languages',
        titleAr: 'دولينجو - تعلم اللغات',
        description: 'Learn a new language for free with the world\'s most-downloaded education app.',
        descriptionAr: 'تعلم لغة جديدة مجاناً مع التطبيق الأكثر تحميلاً في العالم.',
        url: 'https://www.duolingo.com/',
        duration: 'Self-paced',
        level: 'beginner',
        rating: 4.7,
        enrollments: '500M+',
        price: 'Free',
        certificate: false,
        isFree: true,
        featured: false,
        categoryId: categoryMap['languages'],
        languageId: languageMap['en'],
        platformId: platformMap['duolingo'],
      },
      {
        title: 'مقدمة في البرمجة بلغة Python',
        description: 'دورة تعليمية شاملة لتعلم أساسيات البرمجة بلغة بايثون.',
        url: 'https://www.almentor.net/courses/python-intro',
        duration: '20 hours',
        level: 'beginner',
        rating: 4.6,
        price: 'Free',
        certificate: true,
        isFree: true,
        featured: true,
        categoryId: categoryMap['programming'],
        languageId: languageMap['ar'],
        platformId: platformMap['almentor'],
      },
      {
        title: 'Codecademy - Learn HTML & CSS',
        titleAr: 'كود أكاديمي - تعلم HTML و CSS',
        description: 'Learn the basics of web development with HTML and CSS.',
        descriptionAr: 'تعلم أساسيات تطوير الويب باستخدام HTML و CSS.',
        url: 'https://www.codecademy.com/learn/learn-html',
        duration: '9 hours',
        level: 'beginner',
        rating: 4.7,
        price: 'Free',
        certificate: false,
        isFree: true,
        featured: false,
        categoryId: categoryMap['programming'],
        languageId: languageMap['en'],
        platformId: platformMap['codecademy'],
      },
      {
        title: 'Udacity - Intro to Programming Nanodegree',
        titleAr: 'أوداسيتي - مقدمة في البرمجة',
        description: 'Learn the fundamentals of programming with this free course.',
        descriptionAr: 'تعلم أساسيات البرمجة مع هذه الدورة المجانية.',
        url: 'https://www.udacity.com/course/intro-to-programming-nanodegree--nd000',
        duration: '4 months',
        level: 'beginner',
        rating: 4.5,
        price: 'Free',
        certificate: false,
        isFree: true,
        featured: false,
        categoryId: categoryMap['programming'],
        languageId: languageMap['en'],
        platformId: platformMap['udacity'],
      },
    ]

    let createdCount = 0
    for (const course of courses) {
      try {
        await db.course.upsert({
          where: { url: course.url },
          update: course,
          create: course,
        })
        createdCount++
      } catch (e) {
        // Skip if already exists
      }
    }

    return NextResponse.json({
      success: true,
      message: 'Database seeded successfully',
      stats: {
        languages: languages.length,
        categories: categories.length,
        platforms: platforms.length,
        courses: createdCount,
      },
    })
  } catch (error) {
    console.error('Error seeding database:', error)
    return NextResponse.json(
      { success: false, error: 'Failed to seed database' },
      { status: 500 }
    )
  }
}
